PreCommit:
  AuthorName:
    enabled: false
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
  BundleAudit:
    enabled: true

PostCommit:
  CustomScript:
    enabled: true
    required_executable: './bin/lfs/post-commit'

PrePush:
  Brakeman:
    enabled: true
  CustomScript:
    enabled: true
    required_executable: './bin/lfs/pre-push'

PostCheckout:
  ALL: # Special hook name that customizes all hooks of this type
    quiet: true # Change all post-checkout hooks to only display output on failure

  IndexTags:
    enabled: true # Generate a tags file with `ctags` each time HEAD changes

  CustomScript:
    enabled: true
    required_executable: './bin/lfs/post-checkout'

PostMerge:
  CustomScript:
    enabled:
    required_executable: './bin/lfs/post-merge'
