version: '3.4'

x-app: &app
  image: "elct9620/ar-battle-royale:${VERSION:-latest}"
  # TODO: Move unused variable to credentials
  environment:
    - AUTO_MIGRATION=yes
    - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
    - REDIS_URL=redis://redis:6379/1
    - RAILS_MASTER_KEY
    - SENTRY_DSN
  volumes:
      - application_data:/srv/app/public/system
  depends_on:
    - postgres

volumes:
  postgres_data:
    driver: local
  application_data:
    driver: local

services:
  postgres:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  nginx:
    image: "elct9620/ar-battle-royale:${VERSION:-latest}-nginx"
    volumes:
      - application_data:/usr/share/nginx/html/system:ro
    environment:
      - NGINX_APPLICATION_URL=application:3000
      - PUBLIC_PORT
    ports:
      - "$PUBLIC_PORT:$PUBLIC_PORT"
    depends_on:
      - application
  redis:
    image: redis:6.0
  application:
    <<: *app
